### ISSUE TITLE
How to run in Kubernetes.

### ISSUE THREAD

**Issue by cedricve** [pion/turn#195]
I'm trying to run the Pion Turn server in a Kubernetes deployment. However there comes a complexity with the portmapping range. Anyone worked on this already?

**Comment by IdlePhysicist** [comment]
In your deployment.yml add `hostNetwork: true`, under `spec.template.spec`. Please note you will most likely want a dedicated node type for your TURN server then.

**Comment by jech** [comment]
Could you folks please describe what the issue is?  I don't use Kubernetes myself.

**Comment by cedricve** [comment]
@jech, we are deploying our entire solution stack in Kubernetes, and we were wondering to embed pion/turn in there as well.

**Comment by cedricve** [comment]
@IdlePhysicist I tried out but that didnt work (not getting any logs) not sure what is going wrong this is my `main.go` and this is the `deployment.yaml`. I would expect allowHostNetwork do the magic.

Deployment:
https://play.golang.org/p/6CyoApM59wI

Yaml:
https://play.golang.org/p/EXfHgqFP2-L

**Comment by IdlePhysicist** [comment]
Hi @cedricve, my advice would be that you should first try to run this in Docker or Docker Compose on an EC2 (or whatever you use yourself) and see if you have any success. I have compiled your code and ran it locally on my laptop, it appears to work when tested with Coturn's `turn_uclient`, but I have only looked at it for <10 mins.

Looking further at your attached deployment file, I am wondering why you are using an Ingress? As far as I knew they only really supported HTTP(S) but I am rusty on K8s. 

Also I had to use UDP TURN when testing your app, but in your deployment file you define the Service protocol as TCP. Maybe I missed something, or I misused your app?

**Comment by cedricve** [comment]
hey @IdlePhysicist thanks for the response. Well I actually have it running outside a Docker container on a VPS. I can get relay candidates and see the STUN and TURN component in action (logging).

> Also I had to use UDP TURN when testing your app, but in your deployment file you define the Service protocol as TCP. Maybe I missed something, or I misused your app?

Indeed I played around with it and both tried UDP and TCP, both didnt work. I believe this is really K8S specific as not sure what is trying to do. I would expect reaching the ingress `10240` would bring me to the TURN server and create the negotiation and granting of UDP ports (expecting hostNetwork: true) .

> Looking further at your attached deployment file, I am wondering why you are using an Ingress? As far as I knew they only really supported HTTP(S) but I am rusty on K8s.

I also used a plain loadbalancer, and after IP granting I just updated the environment variable of the pod. That didnt work as well.

Thank you so much of helping out, highly appreciated.

**Comment by doctorpangloss** [comment]
You can't use `hostNetwork: true`.

You can't use the `nginx` loadbalancer by itself.

On AWS you have to use the network load balancer they provide. AWS has its own networking API that the load balancer code interacts with to route traffic to your TURN server.

**Comment by cedricve** [comment]
I never was able to make it worked, and ended up with a plain container on a VPS.

**Comment by tbranyen** [comment]
Just wanted to leave a comment in case others hit this same thread. I was able to get this working in kubernetes with rtsp2webrtc and docker using the advice to set `hostNetwork: true`. The caveats I've found are that I cannot run more than a single replicaSet and pod at a time. I need to fully destroy all server groups ahead of a deployment, and only get a single instance. That said, host networking completely solves the problems. Ideally I would know the UDP ports that TURN uses and map those, but this does unblock me.

**Comment by cedricve** [comment]
thanks @tbranyen  could you detail your deployment and steps taken a bit more?

**Comment by tbranyen** [comment]
> thanks @tbranyen could you detail your deployment and steps taken a bit more?

Sure thing. Not sure how you're working with kubernetes, but I'm using it with Spinnaker. I have a pipeline:

![image](https://user-images.githubusercontent.com/181635/199779362-453a180f-9a74-433c-854f-b3309a762f2a.png)

First stage (Bake Image) builds the docker image inside of [rtsp2webrtc](https://github.com/deepch/RTSPtoWebRTC). That repo uses pion/turn under-the-hood. The second stage deletes all kubernetes pods/replicaSets since host networking will all share the same interface and you cannot bind the same port multiple times across multiple pods. This is where the huge caveat with this approach comes in. You can only have a single pod bound to a specific port using host networking. _I suppose with some effort you could make the port value parameterized/randomized for each pod to get around this._

The last stage deploys the manifest that looks like this (note hostNetwork and that I've changed the 8083 port to 9999):

```
apiVersion: v1
kind: Service
metadata:
  name: rtsp2webrtc-app-lb
spec:
  ports:
    - port: 9999
      protocol: TCP
      targetPort: 9999
  selector:
    app: rtsp2webrtc-app-prod
  type: LoadBalancer
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    tier: rtsp2webrtc-app-prod
  name: rtsp2webrtc-app-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: rtsp2webrtc-app-prod
  template:
    metadata:
      labels:
        tier: rtsp2webrtc-app-prod
    spec:
      containers:
        - image: 'rtsp2webrtc-app:latest'
          imagePullPolicy: IfNotPresent
          name: rtsp2webrtc-app-prod
      hostNetwork: true
```

This ends up with a server group with a single instance:

![image](https://user-images.githubusercontent.com/181635/199781080-a9b9b595-2ed0-4506-8b6d-9bd7ceb22731.png)

I point nginx-proxy-manager to the load balancer ip above, and then I get perfect rtsp->webrtc relaying:

![image](https://user-images.githubusercontent.com/181635/199781765-fcdae958-817b-4811-9642-aab6282e0dfd.png)
